/* Granny Plus activation codes for customers who paid by UPI/WhatsApp.
 * Generated by `npm run plus-code -- <puter-username> <monthly|lifetime>`; each entry is a one-way hash
 * of username + plan + code, so codes can't be read from this file or used by another account.
 * Commit and push after adding one: the site redeploys in about a minute. */
export const PLUS_CODES: Array<{ h: string; plan: 'monthly' | 'lifetime'; until: string }> = [
];
